# Generated by Django 2.2.3 on 2019-10-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dep1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('task', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
