# Generated by Django 2.2.3 on 2019-10-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('department', models.CharField(choices=[('1', 'DEPARTMENT 1'), ('2', 'DEPARTMENT 2')], max_length=16)),
                ('task', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'OnProgress'), ('2', 'Completed')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('1', 'DEPARTMENT 1'), ('2', 'DEPARTMENT 2')], max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='dep1',
        ),
        migrations.DeleteModel(
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasklister.User'),
        ),
    ]
